### PR TITLE
Update nuget dependecies

### PR DESCRIPTION
**Pull request by jelleVandendriessche**
Update NJsonSchema package reference to latest version

### CODE REVIEW

**Comment by cvietor** [comment]
This fixes #156

**Comment by cvietor** [comment]
any chances, this can get merged? :-)

**Comment by cvietor** [comment]
this would really help, as this is currently blocking our project from using async api

**Comment by tehmantra** [comment]
This is live in [v0.12.0](https://www.nuget.org/packages/Saunter/0.12.0)

**Pull request merged**
