### PR TITLE
Added support for using Saunter in a proxy-reverse environment

### PR DESCRIPTION
**Pull request by rogerzanelato**
To cover #126.

I put an example on this branch to test the implementation and get some feedback:
```shell
$ cd examples/StreetlightsAPI
$ dotnet publish -c Release
$ docker-compose up

# Open in browser: http://localhost:5000/service-a/asyncapi/ui/index.html
# Open in browser: http://localhost:5000/service-b/asyncapi/ui/index.html
```

### CODE REVIEW

**Comment by rogerzanelato** [comment]
The [first try](https://github.com/tehmantra/saunter/pull/127/commits/11cd43fa037ec4e6631f84749dd68fa2d2c70b59) was with a new "Endpoint" options used exclusively to load the Document JSON.

This could enable using relative paths with the advantage of not nedding to know the base path of the application.

But, a little bug is that although it works fine when accessing http://localhost:5000/service-b/asyncapi/ui/index.html directly, when we visit http://localhost:5000/service-b/asyncapi/ui we got redirected to http://localhost:5000/asyncapi/ui/index.html.

**Comment by rogerzanelato** [comment]
The [second try](https://github.com/tehmantra/saunter/pull/127/commits/b402586646d132eb2529d4a8d997281b360419a4) was with a new "ProxyReverseBasePath" option. This option is gonna be prepend to the redirect and document URL with provided with a string not nullable or empty.

This solved both problems (wrong redirecting and json document not being loaded). I think maybe we could achieve the same result without the new option, taking advantage of the [UseBasePath Middleware](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/Extensions/UsePathBaseExtensions.cs).

If we set the proxy-reverse prefix on the startup like this: `app.UseBasePath("/service-a")`, then we could access this on the Request in our middleware, something like:
```csharp
private string PrependProxyReverseBasePath(HttpRequest httpRequest, string url)
    => httpRequest.PathBase.Add(url);
```

**Comment by rogerzanelato** [comment]
Nope, "UseBathPath" won't work. The problem is that the middleware [extracts the BasePath from the Request](https://github.com/dotnet/aspnetcore/blob/f58f9dcf1c10345a4fa44bbeea4777efd3b0d407/src/Http/Http.Abstractions/src/Extensions/UsePathBaseMiddleware.cs#L51).

It's gonna be empty when using a reverse-proxy like nginx because the request arrives without the prefix.

**Comment by tehmantra** [comment]
Thanks for doing this investigation and testing. Have you tried this with `app.UseBasePath` (from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer)

> If the proxy trims the path (for example, forwarding /foo/api/1 to /api/1), fix redirects and links by setting the request's PathBase property:
```
app.Use((context, next) =>
{
    context.Request.PathBase = new PathString("/foo");
    return next();
});
```

**Comment by rogerzanelato** [comment]
> Thanks for doing this investigation and testing. Have you tried this with `app.UseBasePath` (from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer)
> 
> > If the proxy trims the path (for example, forwarding /foo/api/1 to /api/1), fix redirects and links by setting the request's PathBase property:
> 
> ```
> app.Use((context, next) =>
> {
>     context.Request.PathBase = new PathString("/foo");
>     return next();
> });
> ```

**Comment by rogerzanelato** [comment]
> Thanks for doing this investigation and testing. Have you tried this with `app.UseBasePath` (from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer)
> 
> > If the proxy trims the path (for example, forwarding /foo/api/1 to /api/1), fix redirects and links by setting the request's PathBase property:
> 
> ```
> app.Use((context, next) =>
> {
>     context.Request.PathBase = new PathString("/foo");
>     return next();
> });
> ```

Nice, it works with this suggestion!

I modified the `AsyncApiUiMiddleware` to use the `context.Request.PathBase` to create the redirection and document endpoints, now it works in a proxy-reverse environment when the middleware is applied, but also works in normal circumstances.

**Comment by tehmantra** [comment]
Looks good. Do you want to mark this as non-draft and I can get it merged and get a new version released.

**Comment by rogerzanelato** [comment]
> Looks good. Do you want to mark this as non-draft and I can get it merged and get a new version released.

Done!

**Pull request merged**
